### PR TITLE
#Add Create Code_Of_Conduct.md

### LINKED ISSUE #1: Add Code of Conduct
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow these instructions on how to add a Code of Conduct.

Sample: https://github.com/Girlscript-WOB/Guidelines/blob/main/Project%20Admins/Code%20of%20conduct.md

### PR DESCRIPTION
**Pull request by KiranBaliga**
This is a PR related to the addition of code of conduct page for Gluon Project for their users and contributors. Modified based on the project and added the author's email for reporting purposes. Please review the PR and share the feedback. Please add wob24 and level1 labels. Thank you!

Closes #1

### CODE REVIEW

**Comment by Makul0** [comment]
before contributing to the project first you should know about it, here i am providing link which guide you about the project

**Comment by KiranBaliga** [comment]
Sure, I will be more than happy to read it and make adjustments.

**Comment by Makul0** [comment]
here you go https://jumpy-danthus-351.notion.site/Gluon-mechanism-8561debf03f244edabd18427155b3ce8

**Comment by KiranBaliga** [comment]
@Makul0 I will review the notion notes and redesign from scratch.

**Comment by KiranBaliga** [comment]
@Makul0 Please review the updated commit.

**Comment by KiranBaliga** [comment]
Thank you! is it possible to add level1 and wob24 labels. 🙏💫✨

**Pull request merged**
